### ISSUE TITLE
a small question

### ISSUE THREAD

**Issue by JustCoolPig** [zhaohengz/LLaMP#2]
There is something wrong with data/coop/meta_dataset.py.
I was unable to find the class "DatasetCoOp"，how should i do to solve this problem？
![微信图片_20240630163608](https://github.com/zhaohengz/LLaMP/assets/40169690/d0349cd1-a013-4682-8920-2c96d73c6b1f)

**Comment by zhaohengz** [comment]
Hi,

Thanks for asking. 

It is supposed to be `MetaDataset`. Will fix it shortly.
